version: 2

sources:
  - name: musi_graph_ready
    tables:
      - name: spotify_artists
        identifier: spotify_artists_ready
        description: A list of artists from Spotify's API
      - name: spotify_songs_features
        identifier: spotify_songs_features_ready
        description: An extended table of features per song from Spotify's API
      - name: spotify_user_behaviour_clean
        identifier: spotify_user_behaviour_clean
        description: User data from Spotify's API
      - name: spotify_sleep_playlist
        identifier: spotify_sleep_playlist_ready
        description: Songs from a particular playlist
      - name: spotify_study_playlist
        identifier: spotify_study_music_ready
        description: Songs from a particular playlist
      - name: genres
        identifier: genres_ready
        description: A list of musical genres
      - name: ssd_songs
        identifier: ssd_songs_with_audio_feature_clean_ready
        description: Moar data from Spotify's API
      - name: ssd_artists
        identifier: ssd_artists_ready
        description: Moar data from Spotify's API
      - name: raw_artists
        identifier: raw_artists_ready
        description: Moar data from Spotify's API

#models:
#    - name: staging
#      description: "A staging dbt model"
#      columns:
#          - name: id
#            description: "The primary key for this table"
#            tests:
#                - unique
#                - not_null