
version: 2

sources:
  - name: raw
    schema: project-end-of-batch.musi_graph
#    tables:
#      - name:
#        identifier: 

models:
    - name: staging
      description: "A staging dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: intermediate
      description: "An intermediate dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: mart
      description: "A mart dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
